### ISSUE TITLE
Illegal base64 character when decode pem file

### ISSUE THREAD

**Issue by nicolaslattuada** [CleverTap/apns-http2#13]
Hi
I get the following error when I try to use your library with a pem file (PKCS8).

Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character a
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at com.clevertap.apns.internal.JWT.ES256(JWT.java:70)
	at com.clevertap.apns.internal.JWT.getToken(JWT.java:60)
	at com.clevertap.apns.clients.SyncOkHttpApnsClient.buildRequest(SyncOkHttpApnsClient.java:222)
	at com.clevertap.apns.clients.AsyncOkHttpApnsClient.push(AsyncOkHttpApnsClient.java:87)

Any idea how to fix it?

**Comment by judepereira** [comment]
@nicolaslattuada What did you do to resolve this?

**Comment by nicolaslattuada** [comment]
I am migrating from a pem file with cert and pkcs1 key, so I convert them to p12 using bouncy castle and use the generated certificate for sending. Don't mind the issue that might be that my certificate was not well generated.
