### ISSUE TITLE
Unable to extract the trust manager

### ISSUE THREAD

**Issue by iosnewbie2016** [CleverTap/apns-http2#25]
Hi - Thanks for the library. Really good one. 

I'm trying to run the code on IBM WAS 8.5.5 and am receiving an exception. Details below. Can you pls help me on how to address this? Am trying with Synchronous mode of sending push message. Pls let me know if you need more details.

```
Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$JdkWithJettyBootPlatform@aeaa4bd5, sslSocketFactory is class com.ibm.jsse2.SSLSocketFactoryImpl
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:187)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:60)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
        at com.clevertap.apns.clients.SyncOkHttpApnsClient.<init>(SyncOkHttpApnsClient.java:79)
```

**Comment by judepereira** [comment]
Hey @iosnewbie2016, I've never seen this before. As this pertains to OkHttp, could you please ask there?
