### ISSUE TITLE
SSLHandshakeException when using with p8 option

### ISSUE THREAD

**Issue by iosnewbie2016** [CleverTap/apns-http2#26]
Hi - Am trying to use the library with p8 file (Key Id/Team ID/ P8 option) and when I execute it, the response object is as below. It throws a SSLHandshakeException. I have installed the *.push.apple.com SSL certificate in the WAS trust store. Can you pls guide me on what could cause the issue? My environment is IBM WAS 8.5.5, running Java 1.7. I'm using latest version of OKHTTP3 (3.9.2) since I ran into some trust manager issues with 3.2 version.

NotificationResponse{error=null, httpStatusCll', cause=javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure}

I googled for the problem, but most of the solutions are with p12 option, with certificate not extracted correctly. But am using a p8 file here.

Pls let me know if you need more details. Thanks a bunch for this wonderful library.

**Comment by judepereira** [comment]
I've seen often when there's no ALPN library in the boot class path. Are you certain that it's available in your bootclasspath?

See more info about ALPN [here](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html) and [here](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions).

**Comment by iosnewbie2016** [comment]
Yes. I have ALPN in my class path. That’s why am not sure of the cause for the issue.

**Comment by judepereira** [comment]
Could you try to debug the connection setup and see the cause of the failure? To start with, can print the stack trace contained in NotificationResponse's cause?

**Comment by iosnewbie2016** [comment]
Hi - This is the stack trace.  I use okhttp3 version 3.9.2 Thanks for your help.

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
   at com.ibm.jsse2.j.a(j.java:23)
   at com.ibm.jsse2.j.a(j.java:21)
   at com.ibm.jsse2.qc.b(qc.java:465)
   at com.ibm.jsse2.qc.a(qc.java:451)
   at com.ibm.jsse2.qc.h(qc.java:759)
   at com.ibm.jsse2.qc.a(qc.java:353)
   at com.ibm.jsse2.qc.startHandshake(qc.java:800)
   at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
   at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
   at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
   at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
   at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
   at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
   at okhttp3.RealCall.execute(RealCall.java:77)
   at com.clevertap.apns.clients.SyncOkHttpApnsClient.push(SyncOkHttpApnsClient.java:271)

**Comment by iosnewbie2016** [comment]
Yes. Java 1.7 running on WAS 8.5.5.

**Comment by judepereira** [comment]
I looked up com.ibm.jsse2 (as it's present in your stack trace). It seems that WAS specifies it's own SSL socket factory.

Ignoring the WAS bit here (as I've never used it), the most common cause of ```Received fatal alert: handshake_failure``` is an incorrect .p8 file. Could you please show me the code you're using to initialise the library? You may truncate the actual .p8 token in the middle (I'd like to see the 10 characters in the beginning as well as the end).  

Other information may be masked.

**Comment by judepereira** [comment]
Also, just to be clear, what's the output of java -version?

**Comment by iosnewbie2016** [comment]
The Java version is java_1.7_64 . There is no issue with the p8 file as the code runs fine from a tomcat environment.  But it does not work from the IBM WAS environment. 

Yes, WAS specifies its own SSL socket factory.

**Comment by judepereira** [comment]
Oh, in that case, it must be because of the custom SSL socket factory. You'd need to take this up with WAS support.
