### ISSUE TITLE
java.io.IOException: unexpected end of stream on Connection

### ISSUE THREAD

**Issue by JackZhangOnly** [CleverTap/apns-http2#31]
got an error when pushed
java.io.IOException: unexpected end of stream on Connection{api.development.push.apple.com:443, proxy=DIRECT hostAddress=api.development.push.apple.com/17.188.166.27:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}

Caused by: java.io.EOFException: \n not found: limit=159 content=000018040000000000000100001000000300000001000500004000000600001f…

this is my pom.xml  
[pom.txt](https://github.com/CleverTap/apns-http2/files/1581433/pom.txt)

**Comment by JackZhangOnly** [comment]
IOException is solved(run with alpn agent),but a new error occured

[jetty-alpn-agent] Using: alpn-boot-8.1.10.v20161026.jar
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
[jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
[jetty-alpn-agent] Replacing: sun/security/ssl/Alerts
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:203)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:162)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2033)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:25

**Comment by judepereira** [comment]
Which JRE, and Java version?

**Comment by JackZhangOnly** [comment]
java version 1.8.0_144
VM options:-Xbootclasspath/p:/Users/jackzhang/Downloads/alpn-boot-8.1.11.v20170118.jar

When i remove the alpn setting in pom.xml and run with VM options above ,the following message was received:

NotificationResponse{error=InvalidProviderToken, httpStatusCode=403, responseBody='{"reason":"ExpiredProviderToken"}', cause=null}

**Comment by judepereira** [comment]
@JackZhangOnly Since your connection to APNs is now working, you need to check your provider token. The response ```{"reason":"ExpiredProviderToken"}``` comes directly from APNs.
