### ISSUE TITLE
Certificate should contain "push" keyword

### ISSUE THREAD

**Issue by rohitsahay2000** [CleverTap/apns-http2#46]
Hi,
The apns cert that we are using to send notification doesn't contain"push" keyword for CN. You have a check present for "push" keyword while validating the certificate and there are many others where you check specific strings to be present in the apns cert. 

Due to this issue we are not able send notifications because cert validation fails. Please help what we can do here.

**Comment by judepereira** [comment]
Out of curiosity, what does your certificate’s CN say? Please mask out the bundle ID, team ID and anything else that’s sensitive.

**Comment by rohitsahay2000** [comment]
CN is like this: CN=APSP:0226d278-d925-4044-af07-a346da05e2c5/C=IN

**Comment by judepereira** [comment]
@rohitsahay2000 Until now, all the certificates issued by Apple have contained those strings. It validates the certificate and ensures that you don't accidentally try to use your developer certificate (which has happened many times in the past).

I'll issue a new certificate for APNs tomorrow and check the CN on it.

**Comment by rohitsahay2000** [comment]
@judepereira : Did you check? Have we removed the hardcoding?

**Comment by drunkendaddy** [comment]
any update on this?

I just downloaded a production certificate and it has CN=Apple Development IOS Push Services: myBunldleId

I doubled checked. It is the production certificate and it has development in it.

**Comment by chanoo** [comment]
java.security.cert.CertificateException: Not a push certificate - VoIP Services: com.test.app
	at com.clevertap.apns.CertificateUtils.validateCertificate(CertificateUtils.java:135)
	at com.clevertap.apns.clients.SyncOkHttpApnsClient.<init>(SyncOkHttpApnsClient.java:131)
	at com.clevertap.apns.clients.AsyncOkHttpApnsClient.<init>(AsyncOkHttpApnsClient.java:72)
	at com.clevertap.apns.clients.ApnsClientBuilder.build(ApnsClientBuilder.java:170)

**Comment by nthung82** [comment]
hi
I am facing with is bug
how to slove it?

**Comment by DziubaR** [comment]
It would be great to be able to change behavior with some boolean flag. (include verifying or not)
