### ISSUE TITLE
unexpected end of stream on okhttp3.Address@2f8c2e51

### ISSUE THREAD

**Issue by chenqin091017** [CleverTap/apns-http2#57]
I have the same issue using java 11.
## Error Message
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by okhttp3.internal.Platform (file:/usr/local/repositories/bcc_repositories/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.jar) to field sun.security.ssl.SSLSocketFactoryImpl.context
WARNING: Please consider reporting this to the maintainers of okhttp3.internal.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.io.IOException: unexpected end of stream on okhttp3.Address@2124d4cd
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:199)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
```
```
Caused by: java.io.EOFException: \n not found: size=159 content=000018040000000000000100001000000300000001000500004000000600001f...
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	... 67 more
```
## My Code
```
final ApnsClient client = new ApnsClientBuilder()
                    .inSynchronousMode()
                    .withProductionGateway()
                    .withApnsAuthKey("this is my auth key")
                    .withTeamID("this my teamed")
                    .withKeyID("this is key id")
                    .withDefaultTopic("this is topic")
                    .build();
            Notification n = new Notification.Builder("this is my device token")
                    .alertBody("Hello").build();
            client.push(n);
```
## Some Adjustment
- add class NetInterceptor implements Interceptor
```
@Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request().newBuilder()
                .addHeader("Connection","close").build();
        return chain.proceed(request);
    }
```
-  adjust com.clever.apns.clients.ApnsClientBuilder
```
public static Builder createDefaultOkHttpClientBuilder() {
        Builder builder = new Builder();
        builder.connectTimeout(10, TimeUnit.SECONDS).writeTimeout(10, TimeUnit.SECONDS).readTimeout(30, TimeUnit.SECONDS);
        builder.connectionPool(new ConnectionPool(10, 10, TimeUnit.MINUTES));
        builder.addInterceptor(new NetInterceptor());//added code
        builder.retryOnConnectionFailure(true);//added code
        return builder;
    }
```
- I read apple apps documentation,so I try to add port 2197.
<img width="1578" alt="屏幕快照 2019-05-09 下午8 19 11" src="https://user-images.githubusercontent.com/17311435/57453059-f35b8400-7297-11e9-90ed-1d6daef36625.png">

## Result
But I can not solve the problem.Could you tell me the solution?

**Comment by HELLOYUANJIE** [comment]
I reported the same error as you, and the console printed ALPN callback drop: HTTP/2 is disabled. Is alpn-boot on the boot class path?, the author wrote to ensure that there is Jetty's ALPN JAR in the boot class path (OkHttp needs it), but I don't know which jar was introduced correctly.

**Comment by pavangaddam4** [comment]
I am also getting same error
